//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v8.13.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	// Mixin Content Type with alias "editorDeTextoEnriquecido"
	/// <summary>Editor De Texto Enriquecido</summary>
	public partial interface IEditorDeTextoEnriquecido : IPublishedElement
	{
		/// <summary>Texto A Formatear</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.13.0")]
		global::System.Web.IHtmlString TextoAformatear { get; }
	}

	/// <summary>Editor De Texto Enriquecido</summary>
	[PublishedModel("editorDeTextoEnriquecido")]
	public partial class EditorDeTextoEnriquecido : PublishedElementModel, IEditorDeTextoEnriquecido
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.13.0")]
		public new const string ModelTypeAlias = "editorDeTextoEnriquecido";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.13.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.13.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.13.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<EditorDeTextoEnriquecido, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public EditorDeTextoEnriquecido(IPublishedElement content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Texto A Formatear
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.13.0")]
		[ImplementPropertyType("textoAFormatear")]
		public virtual global::System.Web.IHtmlString TextoAformatear => GetTextoAformatear(this);

		/// <summary>Static getter for Texto A Formatear</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.13.0")]
		public static global::System.Web.IHtmlString GetTextoAformatear(IEditorDeTextoEnriquecido that) => that.Value<global::System.Web.IHtmlString>("textoAFormatear");
	}
}
